### ISSUE TITLE
Whatsapp and facebook on ios 8

### ISSUE THREAD

**Issue by socialraving** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#307] opened 2015-02-20 23:41 UTC
Hi Eddy,

We use your plugin in our app and it works perfectly on android. But on ios8 we only get the default options like mail and ibooks. Do you know of this problem and by change do you know a solution to this problem?

So in short we are looking for a way to share to (mainly) whatsapp and facebook on IOS8.

Thanks in advance

**Comment by EddyVerbruggen** [comment] 2015-02-21 06:43
Dupe of #255

**Closed by EddyVerbruggen** 2015-02-21 06:43 UTC
