### ISSUE TITLE
Social sharing Plugin does not work for ios

### ISSUE THREAD

**Issue by jinqifeng** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#926] opened 2018-03-06 03:38 UTC
This is a free plugin for which I'm no longer able to offer free support.

If you want me to look at your issue with priority (or at all) you may want to consider giving my PayPal account a bit of love. Details are in the readme.

Thank you,
Eddy

**Comment by jinqifeng** [comment] 2018-03-06 03:40
when use shareVia Twitter function, following error apear.
it is same for facebook, instagram.

SLExtensionLazyMatcher for com.apple.share.Twitter.post continuous discovery block got extensions (
"<NSExtension: 0x107f71b00> {id = com.apple.share.Twitter.post}"
) error (null)
2018-03-05 17:27:18.447293+0800 ImageLogo[8021:2979151] [core] SLComposeViewController initWithServiceType got extension <NSExtension: 0x107f71b00> {id = com.apple.share.Twitter.post} for identifier com.apple.share.Twitter.post
2018-03-05 17:27:18.447393+0800 ImageLogo[8021:2979151] [core] SLComposeViewController initWithExtension: <NSExtension: 0x107f71b00> {id = com.apple.share.Twitter.post} requestedServiceType: com.apple.social.twitter
2018-03-05 17:27:18.472811+0800 ImageLogo[8021:2979151] [core] SLComposeViewController dealloc <SLComposeViewController: 0x109e5e3e0>
2018-03-05 17:27:40.599542+0800 ImageLogo[8021:2979151] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present a nil modal view controller on target <MainViewController: 0x1017654d0>.'

**Comment by EddyVerbruggen** [comment] 2018-03-06 06:50
Duplicate of #925

**Closed by EddyVerbruggen** 2018-03-06 06:50 UTC
