### ISSUE TITLE
Sending null or '' in file parameter cause an error in Android URL_NOT_SUPPORTED

### ISSUE THREAD

**Issue by tavojavi** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#415] opened 2015-09-16 18:11 UTC
files.lenght() is allways 1 no matter if I pass null or '' from javascript call...

I fixed this wrapping the if statement and adding a check like this in the file SocialSharing.java line 179

try {
          if ((files.length() > 0) && (!(files.getString(0).equals("")))) {

} catch (Exception e) {
              callbackContext.error(e.getMessage());
            }

Best regards,
Gustavo

**Comment by EddyVerbruggen** [comment] 2015-09-17 14:43
Hi Gustavo,

Thanks for reporting this.

I couldn't reproduce the problem with a null param (probably you can with a "null" param, with quotes), but passing in '' as image(array) indeed resulted in this problem.

I've pushed a fix just now.

**Closed by EddyVerbruggen** 2015-09-17 14:43 UTC
