### ISSUE TITLE
Failed to find configured root that contains - Twitter Android

### ISSUE THREAD

**Issue by junerockwell** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#755] opened 2017-01-18 18:52 UTC
The full error message is: `cannnot share via twitter "Failed to find configured root that contains /storage/emulated/0/Android/data/org.cchd.NeonToNature/files/socialsharing-downloads/www.x-services.nl"`

Using: 
- Ionic Modules v1.x
- Ionic CLI v2.1.18
- Cordova-Android v5.2.2
- Cordova CLI v6.4.0
- LG Risio Device H343 with Android OS v6.0 installed
- ngCordova v0.1.27-alpha
- cordova-plugin-x-socialsharing v5.1.4

When a button is clicked, a `$scope` function is triggered having the following code:
````
$scope.shareViaTwitter = function() {
  console.log('[controllers.js] you want to share via twitter');
  
  $cordovaSocialSharing
    .canShareVia(
      "twitter",
      "hello",
       null,
      "http://www.x-services.nl"
  )
  .then(function(result) {
       // Success!
       console.log("can share via twitter...");
       $cordovaSocialSharing
       .shareViaTwitter(
          "hello",
          null,
          "http://www.x-services.nl"
       )
       .then(function() {
          console.log("successfully shared via twitter");
       }, function(err2) {
          console.log("failed to share via twitter " + JSON.stringify(err2));
       });
    }, function(err1) {
      // An error occurred. Show a message to the user
      console.log("cannnot share via twitter " + JSON.stringify(err1));
    });
};
````

The Twitter app for Android is installed and I have successfully logged in to it.

I'm not sure what the error message is or how to fix it. And after multiple attempts, I cannot send a message to Twitter via this mobile app project.

The last time I remember that this plugin worked was last August 2016. And that, the Cordova-Android was version 5.1.1.

Without `.canShareVia()` and only using `.shareViaTwitter()`, the Twitter app shows up. And, I can change the message and tap the `tweet` button. The console log says `"successfully shared via twitter"` but the post never gets posted to Twitter. There are no other messages or notifications from the plugin or the Twitter app if the post was truly a success or a failure. This has also been done multiple times and the posts do not show up on Twitter.

**Comment by macdonst** [comment] 2017-01-20 19:33
@junerockwell I believe the issue is that Android no longer likes for file:// paths to be passed around. If you've updated to newer version of Cordova-Android it may be expecting a content:// path instead.

**Comment by macdonst** [comment] 2017-01-20 20:00
This is a duplicate of #754

**Closed** 2017-01-21 14:41 UTC
